"""PDF report generator for PST Image Reader."""

import io
import os
from datetime import datetime

from PIL import Image as PILImage
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Register Chinese/CJK font
FONT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "fonts")
FONT_PATH = os.path.join(FONT_DIR, "NotoSansSC-Regular.ttf")
CJK_FONT = "Helvetica"  # fallback

if os.path.exists(FONT_PATH):
    try:
        pdfmetrics.registerFont(TTFont("NotoSansSC", FONT_PATH))
        CJK_FONT = "NotoSansSC"
    except Exception:
        pass


NAVY = HexColor("#1a2744")
NAVY_LIGHT = HexColor("#2d4a7a")
GREEN = HexColor("#16a34a")
RED = HexColor("#dc2626")
GRAY = HexColor("#6b7280")
WHITE = HexColor("#ffffff")
BG_LIGHT = HexColor("#f0f4f8")


# PDF translations
PDF_STRINGS = {
    "en": {
        "title": "PST Image Reader",
        "subtitle": "puriSCOPE Test Report",
        "date": "Date",
        "location": "Location",
        "testId": "Test ID",
        "notes": "Notes",
        "result": "Result",
        "pstValue": "PST VALUE",
        "sampleImages": "Sample Images",
        "standard": "Standard (Reference)",
        "testSample": "Test Sample (Result)",
        "colorAnalysis": "Color Analysis",
        "before": "Before",
        "after": "After",
        "imageNotFound": "Image not found",
        "footer": "Generated by PST Image Reader",
        "notClean": "Not Clean",
        "minimal": "Minimal",
        "fair": "Fair",
        "good": "Good",
        "excellent": "Excellent",
    },
    "zh": {
        "title": "PST 图像读取器",
        "subtitle": "puriSCOPE 检测报告",
        "date": "日期",
        "location": "检测地点",
        "testId": "检测编号",
        "notes": "备注",
        "result": "检测结果",
        "pstValue": "PST 值",
        "sampleImages": "样品图片",
        "standard": "标准液（参考）",
        "testSample": "检测样品（结果）",
        "colorAnalysis": "颜色分析",
        "before": "标准液",
        "after": "检测样品",
        "imageNotFound": "图片未找到",
        "footer": "由 PST 图像读取器生成",
        "notClean": "未达标",
        "minimal": "极低",
        "fair": "一般",
        "good": "良好",
        "excellent": "优秀",
    },
    "de": {
        "title": "PST Bildleser",
        "subtitle": "puriSCOPE Testbericht",
        "date": "Datum",
        "location": "Standort",
        "testId": "Test-Nr.",
        "notes": "Notizen",
        "result": "Ergebnis",
        "pstValue": "PST-WERT",
        "sampleImages": "Probenbilder",
        "standard": "Standardlösung (Referenz)",
        "testSample": "Testprobe (Ergebnis)",
        "colorAnalysis": "Farbanalyse",
        "before": "Vorher",
        "after": "Nachher",
        "imageNotFound": "Bild nicht gefunden",
        "footer": "Erstellt mit PST Bildleser",
        "notClean": "Nicht bestanden",
        "minimal": "Minimal",
        "fair": "Ausreichend",
        "good": "Gut",
        "excellent": "Ausgezeichnet",
    },
}

LABEL_MAP = {
    "Not Clean": "notClean",
    "Minimal": "minimal",
    "Fair": "fair",
    "Good": "good",
    "Excellent": "excellent",
}


def _fix_image_orientation(img_path: str) -> str:
    """Rotate image to correct orientation if needed."""
    try:
        img = PILImage.open(img_path)

        exif = img.getexif()
        orientation = exif.get(274)
        if orientation and orientation != 1:
            rotations = {3: 180, 6: 270, 8: 90}
            if orientation in rotations:
                img = img.rotate(rotations[orientation], expand=True)
                corrected_path = img_path + ".corrected.jpg"
                img.save(corrected_path, "JPEG", quality=90)
                return corrected_path

        import numpy as np
        w, h = img.size
        arr = np.array(img.convert("L"))
        top_brightness = arr[:h//4, :].mean()
        bottom_brightness = arr[3*h//4:, :].mean()

        if top_brightness > bottom_brightness + 5:
            img = img.rotate(180)
            corrected_path = img_path + ".corrected.jpg"
            img.save(corrected_path, "JPEG", quality=90)
            return corrected_path

    except Exception:
        pass

    return img_path


def generate_report_pdf(test_data: dict, before_img_path: str, after_img_path: str, lang: str = "en") -> bytes:
    """Generate a PDF report for a test result.

    Args:
        lang: "en", "zh", or "de"

    Returns PDF content as bytes.
    """
    s = PDF_STRINGS.get(lang, PDF_STRINGS["en"])

    # Use CJK font for Chinese, Helvetica for others
    font = CJK_FONT if lang == "zh" else "Helvetica"
    font_bold = CJK_FONT if lang == "zh" else "Helvetica-Bold"

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontName=font_bold, fontSize=22, leading=26, textColor=NAVY, spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"],
        fontName=font, fontSize=11, textColor=NAVY_LIGHT, spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "SectionHead", parent=styles["Heading2"],
        fontName=font_bold, fontSize=13, textColor=NAVY, spaceBefore=10, spaceAfter=6,
    )
    normal_style = ParagraphStyle(
        "CustomNormal", parent=styles["Normal"],
        fontName=font, fontSize=10, textColor=HexColor("#374151"),
    )
    big_value_style = ParagraphStyle(
        "BigValue", parent=styles["Normal"],
        fontName=font_bold, fontSize=32, leading=38, textColor=NAVY,
        alignment=TA_CENTER, spaceBefore=10, spaceAfter=10,
    )

    elements = []

    # Title
    elements.append(Paragraph(s["title"], title_style))
    elements.append(Paragraph(s["subtitle"], subtitle_style))

    # Test info
    created = test_data.get("created_at", datetime.now().isoformat())
    location = test_data.get("location", "—") or "—"
    notes = test_data.get("notes", "—") or "—"

    info_data = [
        [s["date"], str(created)[:19]],
        [s["location"], location],
        [s["testId"], str(test_data.get("id", "—"))],
        [s["notes"], notes],
    ]
    info_table = Table(info_data, colWidths=[70, 350])
    info_table.setStyle(TableStyle([
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("FONTNAME", (0, 0), (0, -1), font_bold),
        ("FONTNAME", (1, 0), (1, -1), font),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 6))

    # PST Result
    pst_value = test_data.get("pst_value", 0)
    is_clean = test_data.get("is_clean", False)
    label_key = LABEL_MAP.get(test_data.get("label", ""), "good")
    label = s.get(label_key, test_data.get("label", ""))
    status_color = GREEN if is_clean else RED

    elements.append(Paragraph(s["result"], heading_style))
    elements.append(Paragraph(f"{pst_value:.2f}", big_value_style))

    status_style = ParagraphStyle(
        "StatusLabel", parent=styles["Normal"],
        fontName=font, fontSize=14, leading=18, textColor=status_color,
        alignment=TA_CENTER, spaceBefore=2, spaceAfter=12,
    )
    elements.append(Paragraph(f"{s['pstValue']} &mdash; {label}", status_style))

    # Images
    elements.append(Paragraph(s["sampleImages"], heading_style))

    img_table_data = [[s["standard"], s["testSample"]]]
    img_row = []
    for img_path in [before_img_path, after_img_path]:
        if os.path.exists(img_path):
            corrected_path = _fix_image_orientation(img_path)
            img = RLImage(corrected_path, width=70 * mm, height=52 * mm)
            img_row.append(img)
        else:
            img_row.append(Paragraph(s["imageNotFound"], normal_style))
    img_table_data.append(img_row)

    img_table = Table(img_table_data, colWidths=[75 * mm, 75 * mm])
    img_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, 0), font_bold),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("TEXTCOLOR", (0, 0), (-1, 0), NAVY),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(img_table)
    elements.append(Spacer(1, 6))

    # Color Analysis
    elements.append(Paragraph(s["colorAnalysis"], heading_style))

    def rgb_str(prefix):
        r = test_data.get(f"{prefix}_rgb_r", 0)
        g = test_data.get(f"{prefix}_rgb_g", 0)
        b = test_data.get(f"{prefix}_rgb_b", 0)
        return f"({r}, {g}, {b})"

    def lab_str(prefix):
        L = test_data.get(f"{prefix}_lab_l", 0)
        a = test_data.get(f"{prefix}_lab_a", 0)
        b = test_data.get(f"{prefix}_lab_b", 0)
        return f"L*{L:.1f}  a*{a:.1f}  b*{b:.1f}"

    color_data = [
        ["", s["before"], s["after"]],
        ["RGB", rgb_str("before"), rgb_str("after")],
        ["CIELAB", lab_str("before"), lab_str("after")],
        ["Delta a*", "", f"{test_data.get('delta_a', 0):.2f}"],
        ["Delta E", "", f"{test_data.get('delta_e', 0):.2f}"],
    ]

    color_table = Table(color_data, colWidths=[70, 170, 170])
    color_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), font_bold),
        ("FONTNAME", (0, 0), (0, -1), font_bold),
        ("FONTNAME", (1, 1), (-1, -1), font),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.5, GRAY),
        ("BACKGROUND", (0, 1), (-1, -1), BG_LIGHT),
        ("TEXTCOLOR", (0, 1), (-1, -1), HexColor("#374151")),
    ]))
    elements.append(color_table)

    # Footer
    elements.append(Spacer(1, 15))
    footer_style = ParagraphStyle(
        "Footer", parent=styles["Normal"], fontName=font, fontSize=8, textColor=GRAY, alignment=TA_CENTER
    )
    elements.append(Paragraph(
        f"{s['footer']} &mdash; {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        footer_style,
    ))

    doc.build(elements)
    return buffer.getvalue()
